@extends("web.include.index")

@section("content")
      <div class="breadcrums-container py-5" style="background-image: linear-gradient(45deg, rgb(0 0 0 / 65%), rgb(0 0 0 / 65%)),url(http://localhost/xcellentinsights/public/web/images/breadcrums/contact-us.jpg);">
    <div class="container pt-5">
        <div class="text-center mt-3">
            <h3 class="breadcrumbs-title  fw-bold text-white">How to Order</h3>
        </div>
    </div>
   </div>
   <div class="agreement-content mt-5">
      <div class="container">
         <div class="row">
            <div class="col-lg-9">
               <div class="agreement-content">
                  <h3 style="color: #002c60; font-weight: bold;">Purchase and License Agreement:</h3>
                  <h6 class="my-3"><strong>LICENSE</strong></h6>
                  <ul >
                     <li><p>All Materials provided by Company are the exclusive copyright of Xcellent Insights. Materials will be made available to you for access and/or download upon submitting payment.</p> </li>
                     <li><p>When accessed and/or downloaded, the Materials, including all files and images contained therein or generated by the Company, and accompanying data are deemed to be licensed to you by the Company.</p></li>
                     <li><p>The terms of the license are detailed in this section depending on the nature of your purchase. Company does not transfer either the title or the intellectual property rights to the Materials, and Company retains full and complete title to the Materials as well as all intellectual property rights therein.</p></li>
                     <li><p>You may not sell, redistribute, or reproduce the Materials, nor may you decompile, reverse-engineer, disassemble, or otherwise convert any associated software to a human-perceivable form. All trademarks and logos are owned by Company or its licensors and you may not copy or use them in any manner.</p></li>
                     <li>
                        <strong>Enterprise License:</strong>
                        <p>
                           The purchase of the electronic copy of all or part of this type of report constitutes a contractual agreement between Xcellent Insights and the Purchaser. Unlimited Users from your organization may access and download the Materials only as required to view the Materials at your business location. All copyright and other notices on the Materials must be kept on the Materials. The company may print copies of the Materials for internal use within organization. The company may not republish or distribute any Materials or do anything else with the Materials that is not specifically permitted in this Agreement.
                        </p>
                     </li>
                     <li>
                        <strong>Single User License:</strong>
                        <p>
                           The purchase of the electronic copy of all or part of this type of report constitutes a contractual agreement between Xcellent Insights and the Purchaser. You may access and download the Materials only as required to view the Materials on your computer/workstation for your individual use, keeping all copyright and other notices on the Materials. You may print a single copy of Material for your use. You may not republish or distribute any Materials or do anything else with the Materials that is not specifically permitted in this Agreement.
                        </p>
                     </li>
                     <li>
                        <strong>Multi User License:</strong>
                        <p>
                          The purchase of the electronic copy of all or part of this type of report constitutes a contractual agreement between Xcellent Insights and the Purchaser. Two to five Users may access and download the Materials only as required to view the Materials at your location. All copyright and other notices on the Materials must be kept on the Materials. The Purchaser may print up to five copies of the Materials. The company may not republish or distribute any Materials or do anything else with the Materials that is not specifically permitted in this Agreement.
                        </p>
                     </li>
                  </ul>
                  <p><strong>If you are placing an order on a company’s behalf, you must be authorized to make the purchase decision. By ordering Materials from the Company, you agree to the terms of this Agreement. You can place your order using following channels:</strong></p>
                  <ul>
                     <li><strong>Ordering by Telephone</strong>
                        <p>
                         Call us on +1 408 627 7717 and speak with our customer service representative to place an order.
                        </p></li>
                     <li><strong>Email Orders</strong>
                        <p>
                         Post all your requirements and queries to sales@xcellentinsights.com and remember to include all your details including billing and delivery address along with the preferred mode of payment. Our executives will get in touch with you within 24-48 hours owing to the high volume of mails we receive.
                        </p></li>
                     <li><strong>Online Delivery</strong>
                        <p>
                          The purchase of the electronic copy of all or part of this type of report constitutes a contractual agreement between Xcellent Insights and the Purchaser. Two to five Users may access and download the Materials only as required to view the Materials at your location. All copyright and other notices on the Materials must be kept on the Materials. The Purchaser may print up to five copies of the Materials. The company may not republish or distribute any Materials or do anything else with the Materials that is not specifically permitted in this Agreement.
                        </p></li>
                     <li><strong>Customization</strong>
                        <p>
                          The purchase of the electronic copy of all or part of this type of report constitutes a contractual agreement between Xcellent Insights and the Purchaser. Two to five Users may access and download the Materials only as required to view the Materials at your location. All copyright and other notices on the Materials must be kept on the Materials. The Purchaser may print up to five copies of the Materials. The company may not republish or distribute any Materials or do anything else with the Materials that is not specifically permitted in this Agreement.
                        </p></li>
                     <li><strong>Cancellation and Refund Policy:</strong>
                        <p>
                        Due to the easily transferable nature of the Materials, we maintain a strict "no return" policy. Therefore, you should read all the information about the Materials before placing your order. The contents of the various Materials are extensively described on the Site in terms of the Materials’ chapters, subchapters, lists of tables and figures. Upon payment, the Company will not accept the cancellation of an order. If you are in any doubt about any transaction, you should contact Xcellent Insights before making a purchase decision and clicking on the purchase button on the xcellent Insights final checkout screen, or by ordering on the telephone or by email.
                        All purchases from the Site are final. Considering the electronic format of the Materials sold, xcellent Insights cannot accept return of products once they have been dispatched. Refunds may be offered under special conditions solely at the discretion of the management. In the event of incomplete or missing information in our research report, xcellent Insights will offer free customization/ad-hoc request for that report.
                        If User feels that an error has occurred in any transaction, User should contact xcellent Insights to discuss the problem with a member of Xcellent Insights customer service team at <strong>sales@xcellentinsights.com</strong>
                        </p></li>
                  </ul>
               </div>
            </div>
            <div class="col-lg-3">
                <div class="faq-sidebar">
                    <div class="row">
                        <div class="col">
                            <div class="sidebar-heading mb-3 pb-3">
                                <h5 style="font-weight: bold;">Related Links</h5>
                            </div>
                            <div class="related-links">
                                <div class="individual-links">
                                    <h6><a href="{{ route('faq') }}">Faq's</a></h6>
                                </div>
                                <div class="individual-links">
                                    <h6><a href="{{ route('order') }}">How To Order</a></h6>
                                </div>
                                <div class="individual-links">
                                    <h6><a href="{{ route('privacy') }}">Privacy Policy</a></h6>
                                </div>
                                <div class="individual-links">
                                    <h6><a href="{{ route('terms') }}">Terms of Use</a></h6>
                                </div>
                                <div class="individual-links">
                                    <h6><a href="{{ route('sitemap') }}">HTML Sitemap</a></h6>
                                </div>
                                <div class="individual-links">
                                    <h6><a href="{{ route('agreement') }}">Purchase & Licensing Agreement</a></h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
      </div>
   </div>
@endsection